"""Generate the provenance + GDPR data card (the documented part of deliverable 1).

Reads the source registry + the **shipped** build artefacts (``data/kaggle_upload/``) and
emits a human-readable card to data/cards/DATA_CARD.md (versioned). The build composition is
computed directly from the shipped JSONL — the trained deliverable — so the card never drifts
from what was actually trained. The GDPR story: all sources are exam questions or public
NIH text + synthetic/constructed annotations — no real patient records — so the constructed
dataset is non-personal by construction (GDPR Recital 26). A Presidio verification pass is
wired separately and its findings get appended here.

Usage:  uv run python -m oc14_triage.data.card
"""

from __future__ import annotations

import collections
import json

from ..config import CARDS, KAGGLE_UPLOAD, RAW, SEED, URGENCY_LEVELS
from .sources import SOURCES


def _load(path):
    return json.loads(path.read_text()) if path.exists() else None


def _read_jsonl(path) -> list[dict]:
    if not path.exists():
        return []
    # split on "\n" only — splitlines() also breaks on  /\v/\f that appear inside record text
    return [json.loads(line) for line in path.read_text().split("\n") if line.strip()]


def _urgency_of(row: dict) -> str:
    """The shipped triage rows carry the urgency only inside the assistant answer."""
    txt = row["messages"][-1]["content"].lower()
    for lv in URGENCY_LEVELS:
        if lv in txt:
            return lv
    return "(unparsed)"


def _counts(rows: list[dict], key: str) -> dict:
    return dict(collections.Counter(r.get(key) for r in rows))


def _sft_stats() -> dict:
    out: dict = {}
    for split, fname in (("train", "sft_train.jsonl"), ("val", "sft_val.jsonl")):
        rows = _read_jsonl(KAGGLE_UPLOAD / fname)
        if not rows:
            continue
        tri = [r for r in rows if r.get("kind") == "triage"]
        out[split] = {
            "n": len(rows),
            "lang": _counts(rows, "lang"),
            "kind": _counts(rows, "kind"),
            "source": _counts(rows, "source"),
            "urgency_in_triage": dict(collections.Counter(_urgency_of(r) for r in tri)),
        }
    return out


def _dpo_stats() -> dict:
    out: dict = {}
    for split, fname in (("train", "dpo_train.jsonl"), ("val", "dpo_val.jsonl")):
        rows = _read_jsonl(KAGGLE_UPLOAD / fname)
        if not rows:
            continue
        out[split] = {
            "n": len(rows),
            "lang": _counts(rows, "lang"),
            "source": _counts(rows, "source"),
        }
    return out


def _eval_stats() -> dict | None:
    rows = _read_jsonl(KAGGLE_UPLOAD / "triage_eval_gold.jsonl")
    if not rows:
        return None
    return {"n": len(rows), "by_level": _counts(rows, "gold_urgency")}


def build() -> str:
    inv = _load(RAW / "_inventory.json") or []
    rows_by_source: collections.Counter[str] = collections.Counter()
    for r in inv:
        if "error" not in r:
            rows_by_source[r["source"]] += r["num_rows"]
    sft = _sft_stats()
    dpo = _dpo_stats()
    gold = _eval_stats()
    audit = _load(CARDS / "anonymization_audit.json")
    if audit:
        _ents = ", ".join(f"{k}={v:,}" for k, v in audit["entities_by_type"].items())
        _verif = (
            f"- **Verification (done — {audit['engine']} {audit['engine_version']}):** ran a Presidio "
            f"pass over {audit['n_records']:,} corpus texts (audit trail `anonymization_audit.json`: "
            f"per-record SHA-256 + entities, no raw text stored). Raw detections: {_ents}. **These are "
            "overwhelmingly clinical eponyms, anatomical LOCATIONs, ages and generic exam personas "
            "(Monsieur/Madame X) — not real patient identifiers**, consistent with the sources being "
            "ECN/pharmacy exam questions + synthetic vignettes (no real patients → Recital 26). The "
            "runtime agent additionally anonymises every input before storage — see `METADATA_SCHEMA.md`."
        )
    else:
        _verif = ("- **Verification (pending):** a Presidio pass is wired in "
                  "`oc14_triage.data.anonymize_audit` — run `python -m oc14_triage.data.anonymize_audit`.")

    lines = [
        "# OC14 — Bilingual medical-triage dataset · provenance & GDPR card",
        "",
        "_Auto-generated by `oc14_triage.data.card`. Source of truth = the markdown research "
        "docs + this card; regenerate after any rebuild. Build composition below is computed "
        "directly from the shipped `data/kaggle_upload/*.jsonl` (the trained deliverable)._",
        "",
        "## Sources",
        "",
        "| Source | HF id | Lang | License | Role | Status | Raw rows |",
        "|---|---|---|---|---|---|---|",
    ]
    for s in SOURCES:
        status = "active" if s.enabled else "DISABLED"
        n = rows_by_source.get(s.name, 0)
        lines.append(f"| {s.name} | `{s.hf_id}` | {s.language} | {s.license} | {s.role} | "
                     f"{status} | {n:,} |")
    lines += [
        "",
        "Per-source notes:",
        "",
    ]
    for s in SOURCES:
        lines.append(f"- **{s.name}** — {s.notes} ([HF]({s.url}))")
    lines += [
        "",
        "> **Note:** `ultramedical_pref` is listed above only as historical provenance for the "
        "**retracted DPO #1**. The **shipped** DPO uses direction-balanced triage-preference pairs "
        "(see Build composition) and does **not** include UltraMedical.",
    ]

    lines += [
        "",
        "## GDPR / RGPD statement",
        "",
        "- **No real patient records.** Sources are (a) French ECN/pharmacy **exam questions** "
        "(MediQAl), (b) public **NIH patient-education** text (MedQuAD), and (c) **constructed / "
        "synthetic** triage answers (the DPO preference pairs are built from the consensus-labelled "
        "cases + hand-written safety pairs). Hand-written triage vignettes are **fictional**.",
        "- The constructed SFT/DPO sets therefore contain **no personally identifiable information**; "
        "they are non-personal by construction → outside GDPR scope (**Recital 26**).",
        "- **MIETIC / MIMIC-derived triage corpora are deliberately excluded** (PhysioNet credentialed "
        "license forbids redistribution) — see research doc 00 §0b / Decision B.",
        _verif,
        "",
        "## Build composition",
        "",
        "_Triage labels are **3-LLM consensus** (GPT-5.4 + Mistral-Medium-3.5 + Sonnet-4.6, "
        "Fleiss κ≈0.67) — not a heuristic; eval-gold is held-out consensus, disjoint from train._",
        "",
    ]
    if sft.get("train"):
        t = sft["train"]
        v = sft.get("val", {})
        lines += [
            f"**SFT** — train {t['n']:,} / val {v.get('n', 0):,} (seed {SEED}).",
            f"- Language: {t['lang']}  (target ~80% fr / 20% en)",
            f"- Kind: {t['kind']}  → triage share = "
            f"{round(100 * t['kind'].get('triage', 0) / t['n'])}%",
            f"- Urgency in triage rows (parsed from the assistant answer): {t['urgency_in_triage']}",
            f"- Source mix: {t['source']}",
            "",
        ]
    if dpo.get("train"):
        t = dpo["train"]
        v = dpo.get("val", {})
        lines += [
            f"**DPO** — train {t['n']:,} / val {v.get('n', 0):,} (seed {SEED}).",
            f"- **Direction-balanced triage-preference pairs**: source {t['source']} — chosen = the "
            "correct level, rejected = a wrong **adjacent** level; `safety` = hand-written bilingual "
            "red-flag pairs.",
            f"- Language: {t['lang']}.",
            "- Framed as a DPO **technique demo + safety lever**, not a clinical-quality signal. "
            "DPO #2 scored 0.80 macro-F1 vs SFT v9's 0.82 (collapsed the middle class) → **not shipped**.",
            "",
        ]
    if gold:
        lines += [
            f"**Evaluation gold** — {gold['n']:,} held-out cases, stratified by urgency level: "
            f"{gold['by_level']}. Used for every reported metric (greedy, leak-free).",
            "",
        ]
    CARDS.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    (CARDS / "DATA_CARD.md").write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    build()
    print(f"Wrote {CARDS / 'DATA_CARD.md'}")
