"""Generate the provenance + GDPR data card (the documented part of deliverable 1).

Reads the source registry + the build artefacts and emits a human-readable card to
data/cards/DATA_CARD.md (versioned). The GDPR story: all sources are exam questions or
public NIH/教科书 text + GPT-4 annotations — no real patient records — so the constructed
dataset is non-personal by construction (GDPR Recital 26). A Presidio verification pass is
wired separately and its findings get appended here.

Usage:  uv run python -m oc14_triage.data.card
"""

from __future__ import annotations

import json

from ..config import CARDS, PROCESSED, RAW
from .sources import SOURCES


def _load(path):
    return json.loads(path.read_text()) if path.exists() else None


def build() -> str:
    inv = _load(RAW / "_inventory.json") or []
    rows_by_source: dict[str, int] = {}
    for r in inv:
        if "error" not in r:
            rows_by_source[r["source"]] = rows_by_source.get(r["source"], 0) + r["num_rows"]
    sft = _load(PROCESSED / "_sft_stats.json")
    dpo = _load(PROCESSED / "_dpo_stats.json")

    lines = [
        "# OC14 — Bilingual medical-triage dataset · provenance & GDPR card",
        "",
        "_Auto-generated by `oc14_triage.data.card`. Source of truth = the markdown research "
        "docs + this card; regenerate after any rebuild._",
        "",
        "## Sources",
        "",
        "| Source | HF id | Lang | License | Role | Status | Raw rows |",
        "|---|---|---|---|---|---|---|",
    ]
    for s in SOURCES:
        status = "active" if s.enabled else "DISABLED"
        n = rows_by_source.get(s.name, 0)
        lines.append(f"| {s.name} | `{s.hf_id}` | {s.language} | {s.license} | {s.role} | "
                     f"{status} | {n:,} |")
    lines += [
        "",
        "Per-source notes:",
        "",
    ]
    for s in SOURCES:
        lines.append(f"- **{s.name}** — {s.notes} ([HF]({s.url}))")

    lines += [
        "",
        "## GDPR / RGPD statement",
        "",
        "- **No real patient records.** Sources are (a) French ECN/pharmacy **exam questions** "
        "(MediQAl), (b) public **NIH patient-education** text (MedQuAD), (c) **synthetic / GPT-4 "
        "annotated** preference data (UltraMedical). Hand-written triage vignettes are **fictional**.",
        "- The constructed SFT/DPO sets therefore contain **no personally identifiable information**; "
        "they are non-personal by construction → outside GDPR scope (**Recital 26**).",
        "- **MIETIC / MIMIC-derived triage corpora are deliberately excluded** (PhysioNet credentialed "
        "license forbids redistribution) — see research doc 00 §0b / Decision B.",
        "- **Verification (pending):** a Microsoft Presidio pass (FR `fr_core_news_md` + EN) is wired "
        "in `oc14_triage.data.anonymize` (TODO) and will run as a *hypothesis test* — we expect "
        "near-zero PII and will report the actual findings here with an audit log (per-record "
        "SHA-256, entities found, timestamp).",
        "",
        "## Build composition",
        "",
    ]
    if sft:
        t = sft["train"]
        lines += [
            f"**SFT** — train {t['n']:,} / val {sft['val']['n']:,}, seed {sft['seed']}.",
            f"- Language: {t['lang']}  (target ~80% fr / 20% en)",
            f"- Kind: {t['kind']}  → triage share = "
            f"{round(100 * t['kind'].get('triage', 0) / t['n'])}%",
            f"- Urgency in triage rows: {t.get('urgency_in_triage', {})} "
            "(urgency is a documented **heuristic** on QA-derived rows; eval vignettes are "
            "hand-labelled independently)",
            f"- Source mix: {t['source']}",
            "",
        ]
    if dpo:
        lines += [
            f"**DPO** — train {dpo['train']['n']:,} / val {dpo['val']['n']:,}, "
            f"{dpo['safety_pairs']} hand-written bilingual safety pairs + "
            f"{dpo['ultramedical_kept']:,} UltraMedical (filtered chosen≥{dpo['filter']['chosen_score>=']}, "
            f"rejected≤{dpo['filter']['rejected_score<=']}).",
            "- Framed as a DPO **technique demo + safety lever**, not a clinical-quality signal.",
            "",
        ]
    CARDS.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    (CARDS / "DATA_CARD.md").write_text(text, encoding="utf-8")
    return text


if __name__ == "__main__":
    build()
    print(f"Wrote {CARDS / 'DATA_CARD.md'}")
